
services:
  postgres:
    image: postgres:15
    container_name: fhir_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fhir_triage
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: fhir_redis
    ports:
      - "6379:6379"

  